trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: "ubuntu-latest"

variables:
  acrName: "huacr"
  resourceGroup: "hu-rad"
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    jobs:
      - job: BuildApp
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "microsoft-azure-sponsorship"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                echo "Logging into ACR..."
                az acr login --name $(acrName)

                if [ "$(Build.SourceBranchName)" == "development" ]; then
                    docker build -t $(acrName).azurecr.io/hurad-fe-dev:$(tag) .
                    docker push $(acrName).azurecr.io/hurad-fe-dev:$(tag)
                elif [ "$(Build.SourceBranchName)" == "main" ]; then
                    docker build -t $(acrName).azurecr.io/hurad-fe-prod:$(tag) .
                    docker push $(acrName).azurecr.io/hurad-fe-prod:$(tag)
                fi
            displayName: "Azure Login, Build and Push Docker Image"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployApp
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "microsoft-azure-sponsorship"
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                if [ "$(Build.SourceBranchName)" == "development" ]; then
                    az containerapp update --name hurad-fe-dev --resource-group $(resourceGroup) --image $(acrName).azurecr.io/hurad-fe-dev:$(tag)
                elif [ "$(Build.SourceBranchName)" == "main" ]; then
                    az containerapp update --name hurad-fe-prod --resource-group $(resourceGroup) --image $(acrName).azurecr.io/hurad-fe-prod:$(tag)
                fi
            displayName: "Deploy to Azure Container Apps"
